# Generated by Django 5.1 on 2024-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('credit', 'クレジットカード'), ('cashless', 'キャッシュレス決済')], default='cash', max_length=10),
        ),
    ]
