# Generated by Django 5.1 on 2024-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_expense_date_alter_income_date'),
        ('budget', '0004_maincategory_rename_category_income_source_and_more'),
    ]

    operations = [
    ]
