# Generated by Django 5.1 on 2024-09-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_source_alter_income_source'),
        ('budget', '0007_patience_user'),
    ]

    operations = [
    ]
