# Generated by Django 5.1.2 on 2024-10-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rating',
            field=models.IntegerField(choices=[(1, 'よかった'), (2, 'ふつう'), (3, '必要なかった')], default=2),
        ),
        migrations.DeleteModel(
            name='Patience',
        ),
    ]
